name: firefile
description: The Firefile package makes it easy to control the display of the Firestore file download progress.
version: 0.6.3
homepage: https://github.com/skyfet/firefile 

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ">=10.2.15 <12.0.0"
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  freezed_annotation: ^2.0.0

dev_dependencies:
  freezed: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

platforms:
  android:
  ios:
  macos:
  web:
  windows: