name: firefile
description: The Firefile package makes it easy to control the display of the Firestore file download progress.
version: 0.1.0
homepage: https://github.com/skyfet/firefile

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^10.2.15
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  freezed: ^2.0.3
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
